version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: localhost
      POSTGRES_DB: social_media
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://localhost:localhost@postgres:5432/social_media"
